name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
       
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Install dependencies
        run: |
          pip install numpy pytest coverage
          pip install -e .

      - name: Run tests with pytest
        run: coverage run --source pathfinding3d -m pytest 

      - name: Show basic test coverage report
        run: |
          coverage report -m
          coverage xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests

      - name: Build docs
        run: |
          pip install sphinx sphinx_rtd_theme sphinx-autodoc-typehints sphinx-copybutton sphinx-prompt sphinx-notfound-page sphinx-version-warning
          sphinx-build -b html docs/ ./public

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
